version: '3'
services:
  app:
    build:
      context: .
      dockerfile: docker/Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      mysql:
        condition: service_healthy

  mysql:
    container_name: hotel-store-case-go-mysql
    command: --default-authentication-plugin=mysql_native_password
    image: mysql:8
    restart: unless-stopped
    environment:
      MYSQL_USER: 'db_user'
      MYSQL_PASSWORD: '123456'
      MYSQL_ROOT_PASSWORD: '123456'
    ports:
      - '3306:3306'
    volumes:
      - './docker/data/mysql8:/var/lib/mysql'
      - './docker/sql/init.sql/:/docker-entrypoint-initdb.d/init.sql'
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p123456" ]
      interval: 10s
      timeout: 5s
      retries: 5

